# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  plugin-citext-enable:
    default: false
    type: boolean
    description: Enable citext extension
  plugin-debversion-enable:
    default: false
    type: boolean
    description: Enable debversion extension
  plugin-hstore-enable:
    default: false
    type: boolean
    description: Enable hstore extension
  plugin-pg_trgm-enable:
    default: false
    type: boolean
    description: Enable pg_trgm extension
  plugin-plpython3u-enable:
    default: false
    type: boolean
    description: Enable PL/Python extension
  plugin-unaccent-enable:
    default: false
    type: boolean
    description: Enable unaccent extension
