# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  plugin-citext-enable:
    default: false
    type: boolean
    description: Enable citext extension
  plugin-hstore-enable:
    default: false
    type: boolean
    description: Enable hstore extension
  plugin-pgtrgm-enable:
    default: false
    type: boolean
    description: Enable pg_trgm extension
  plugin-unaccent-enable:
    default: false
    type: boolean
    description: Enable unaccent extension
