charm_major = 1
workload = "16.13"

[snap]
name = "charmed-postgresql"

[snap.revisions]
# amd64
x86_64 = "313"
# arm64 (Linux)
aarch64 = "314"
# arm64 (macOS / Apple Silicon - same snap revision)
arm64 = "314"
