# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Raft connectivity observer."""

from os import environ
from subprocess import run

from pysyncobj.utility import TcpUtility

# from tenacity import RetryError, Retrying, stop_after_attempt, wait_fixed
from yaml import safe_load

from constants import PATRONI_CONF_PATH, RAFT_PARTNER_PREFIX, RAFT_PORT

PATRONI_CONF_FILE_PATH = f"{PATRONI_CONF_PATH}/patroni.yaml"


def dispatch(custom_event):
    """Use the input juju-run command to dispatch a custom event."""
    dispatch_sub_cmd = "JUJU_DISPATCH_PATH=hooks/{} {}/dispatch"
    # Input is generated by the charm
    run([  # noqa: S603
        "/usr/bin/juju-exec",
        "-u",
        environ["JUJU_UNIT_NAME"],
        dispatch_sub_cmd.format(custom_event, environ["JUJU_CHARM_DIR"]),
    ])


def get_raft_password() -> str | None:
    """Get the raft password from the patroni config file."""
    try:
        with open(PATRONI_CONF_FILE_PATH) as conf_file:
            conf_file_contents = safe_load(conf_file)
            return conf_file_contents["raft"]["password"]
    except Exception as e:
        print(f"Unable to get password: {e}")


def check_raft_connection(password: str) -> None:
    """Verify that the watcher has joined the Raft cluster."""
    # Get the status of the raft cluster.
    syncobj_util = TcpUtility(password=password, timeout=3)

    try:
        raft_status = syncobj_util.executeCommand(f"127.0.0.1:{RAFT_PORT}", ["status"])
    except Exception:
        print("Cannot connect to local Raft")
        return
    print(f"Local raft: {raft_status}")
    for key in raft_status:
        if key.startswith(RAFT_PARTNER_PREFIX) and raft_status[key] != 2:
            addr = key.split(RAFT_PARTNER_PREFIX)[-1]
            try:
                print(f"{addr} Raft: {syncobj_util.executeCommand(addr, ['status'])}")
            except Exception:
                print(f"Unable to connect to {addr}")
                continue
            print(f"Potentially stuck connection with {addr}")
            dispatch("raft_reconnect")


def main() -> None:
    """Main watch and dispatch."""
    if not (password := get_raft_password()):
        return
    check_raft_connection(password)


if __name__ == "__main__":
    main()
